name: Tests
on:
  push:
    branches: [ main, vue-router-v4.0.12 ]
  pull_request:
    branches: [ main, vue-router-v4.0.12 ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version:  ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    # - name: Install Playwright
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: yarn playwright test
    # - uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
    - name: Run Vue-i18n tests
      run: |
        cd src/pages/VueCore/Vue-i18n
        yarn
        yarn test:e2e
    - name: Run VueRouter tests
      run: |
        cd src/pages/VueCore/VueRouter/e2e
        yarn
        yarn add chromedriver@98
        yarn test:e2e:headless
